#!/usr/bin/env bash
# Bash script that redirects to another page
sudo apt-get -y update
sudo apt-get -y install nginx
echo "Holberton School" > /var/www/html/index.nginx-debian.html
echo "server {
    listen 80;
    listen [::]:80 default_server;
    root   /var/www//html;
    index index.nginx-debian.html index.nginx-debian.html;
    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
}" > /etc/nginx/sites-available/default
service nginx restart
