#!/usr/bin/env bash
# Bash Script that redirects to another page
sudo apt-get -y update
sudo apt-get -y install nginx
redir="location /redirect_me {\nrewrite ^/(.*)$ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;\n}\n"
sudo sed -i "29i $redir" /etc/nginx/sites-available/default
service nginx restart
