#!/usr/bin/env bash
# Bash Script that redirects to another page
sudo apt-get -y update
sudo apt-get -y install nginx
sudo chmod 777 /var/www/html/index.nginx-debian.html
echo "Holberton School" > /var/www/html/index.nginx-debian.html
sudo sed '3 a rewrite  ^/redirect_me/$  http://localhost/cirine.html permanent;' /etc/nginx/sites-available/default
sudo service nginx restart
