#!/usr/bin/env bash
# Bash Script that configures Nginx so that its HTTP response contains a custom header (on web-01 and web-02
sudo apt -y update
sudo apt-get -y install nginx
sudo chmod 777 /var/www/html/index.nginx-debian.html
echo "Holberton School" > /var/www/html/index.nginx-debian.html
echo "server {                                                                  
    listen 80;                                                                  
    listen [::]:80 default_server;                                              
    root   /var/www//html;                                                      
    index index.nginx-debian.html index.nginx-debian.html;
    add_header X-Served-By $HOSTNAME;                    
                                                                     
}" > /etc/nginx/sites-available/default
sudo service nginx restart