#!/usr/bin/env bash
# Bash script that generates a MySQL dump and then creates a compressed archive out of it

mysqldump -u root -p$1 --opt --all-databases > backup.sql
tar -zcvf "$(date +'%d-%m-%y')".tar.gz backup.sql
