#!/usr/bin/env bash
# This script is diplaying time for 12 hours & 59 minutes
i=0
while ((i <= 12))
do
    echo Hour: $i
    j=1
    while ((j <= 59))
    do
        echo $j
        ((j++))
    done
    ((i++))
done
