#!/usr/bin/env bash
# This script is displaying informations about a file
file="holbertonschool"
if [ ! -e "$file" ]
then
    echo holbertonschool file does not exist
else
    echo holbertonschool file exists
    if [ ! -s "$file" ]
    then
        echo holbertonschool file is empty
    else
        echo holbertonschool file is not empty
    fi
    if [ -f "$file" ]
    then
        echo holbertonschool is a regular file
    fi
fi